[project]
name = "desktop-drifter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyqt6>=6.10.2",
    "pyobjc-framework-Cocoa>=10.0; sys_platform == 'darwin'",
]
